using System;
using System.Collections.Generic;
using System.Text;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("LiveUnitTesting.GrpcClient.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b1f597635c44597fcecb493e2b1327033b29b1a98ac956a1a538664b68f87d45fbaada0438a15a6265e62864947cc067d8da3a7d93c5eb2fcbb850e396c8684dba74ea477d82a1bbb18932c0efb30b64ff1677f85ae833818707ac8b49ad8062ca01d2c89d8ab1843ae73e8ba9649cd28666b539444dcdee3639f95e2a099bb2")]

namespace LiveUnitTesting.GrpcClient
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Http;
    using System.Text.Json;
    using System.Threading;
    using System.Threading.Tasks;
    using Grpc.Core;
    using Google.Protobuf;
    using Autogenerated = Autogen.Grpc.v1;
    using System.Net.Http.Json;
    using Google.Protobuf.WellKnownTypes;
    using Grpc.Net.Client;

    /// <summary>
    /// A client for interacting with the Dapr endpoints.
    /// </summary>
    public class DaprClientGrpc : DaprClient
    {
        private readonly Autogenerated.Dapr.DaprClient client;

        internal Autogenerated.Dapr.DaprClient Client => client;

        /// <summary>
        /// 
        /// </summary>
        public DaprClientGrpc()
        {
            var grpcEndpoint = new Uri("bla://");

            var channel = GrpcChannel.ForAddress(grpcEndpoint);

            this.client = new Autogenerated.Dapr.DaprClient(channel);
        }
    }
}
